[package]

name = "js"
version = "0.1.0"
authors = ["The Servo Project Developers"]

build = "build.rs"

[features]
debugmozjs = ['mozjs_sys/debugmozjs']

[dependencies.mozjs_sys]
git = "https://github.com/tschneidereit/mozjs"
version = "*"

[dependencies]
libc = "*"
rustc-serialize = "*"
log = "*"
heapsize = "0.1.1"
